/**
 * Development seed.
 *
 * Creates an administrator, two client accounts with realistic order history,
 * and a set of certificates covering every status the verification page can
 * render — released, private, revoked — so the whole flow is exercisable
 * immediately after `npm run db:seed`.
 *
 * Idempotent: re-running updates the fixed accounts rather than duplicating
 * them, and skips seeding entirely if certificates already exist.
 *
 * The placeholder PDFs written here are minimal but genuinely valid PDF files,
 * so the magic-number check in the upload path and the browser's PDF viewer
 * both behave exactly as they would with a real certificate.
 */

import { PrismaClient, type CertificateResult } from "@prisma/client";
import bcrypt from "bcryptjs";
import { createHmac, randomBytes } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const prisma = new PrismaClient();

const HASH_SECRET =
  process.env.CERTIFICATE_HASH_SECRET ?? "development-only-hash-secret";

const TOKEN_ALPHABET =
  "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789";

function token(length = 28): string {
  const bytes = randomBytes(length * 2);
  let out = "";
  for (let i = 0; out.length < length; i++) {
    const byte = bytes[i % bytes.length];
    if (byte < 256 - (256 % TOKEN_ALPHABET.length)) {
      out += TOKEN_ALPHABET[byte % TOKEN_ALPHABET.length];
    }
  }
  return out;
}

function sha256Hex(data: Buffer): string {
  return createHmac("sha256", "sha256-stand-in").update(data).digest("hex");
}

function certificateHash(input: {
  certificateNumber: string;
  customerName: string;
  product: string;
  batchNumber: string;
  issuedDate: Date;
  pdfSha256: string;
}): string {
  const canonical = [
    input.certificateNumber,
    input.customerName.trim(),
    input.product.trim(),
    input.batchNumber.trim(),
    input.issuedDate.toISOString().slice(0, 10),
    input.pdfSha256,
  ].join("|");
  return createHmac("sha256", HASH_SECRET).update(canonical).digest("hex");
}

/** Minimal but structurally valid single-page PDF. */
function placeholderPdf(title: string, subtitle: string): Buffer {
  const escape = (value: string) => value.replace(/[()\\]/g, "\\$&");
  const content = `BT /F1 20 Tf 60 720 Td (${escape(title)}) Tj ET
BT /F1 11 Tf 60 694 Td (${escape(subtitle)}) Tj ET
BT /F1 9 Tf 60 660 Td (Placeholder document generated by the development seed.) Tj ET
BT /F1 9 Tf 60 646 Td (Replace with a real Certificate of Analysis before production use.) Tj ET`;

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];

  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "latin1");
}

/**
 * Writes a placeholder object.
 *
 * Only supports the local driver — seeding into a real Supabase bucket would
 * put fake certificates into production storage, which is exactly the mistake
 * this guard exists to prevent.
 */
async function writeLocalObject(key: string, body: Buffer): Promise<void> {
  if ((process.env.STORAGE_DRIVER ?? "local") !== "local") {
    console.warn(
      `  ! STORAGE_DRIVER is not "local" — skipping placeholder PDF for ${key}.\n` +
        "    Seeded certificates will have no document behind them.",
    );
    return;
  }
  const target = resolve(process.cwd(), ".storage", key);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, body);
}

async function main() {
  console.log("\n▸ Seeding LAVA Diagnostics\n");

  const existing = await prisma.certificate.count();
  if (existing > 0) {
    console.log(
      `  Database already contains ${existing} certificate(s). Skipping.\n` +
        "  Reset with `npx prisma migrate reset` to reseed from scratch.\n",
    );
    return;
  }

  // ── Administrator ──
  const adminEmail = (
    process.env.SEED_ADMIN_EMAIL ?? "admin@lavadiagnostics.com"
  ).toLowerCase();
  const adminPassword = process.env.SEED_ADMIN_PASSWORD ?? "ChangeMe!2026";

  const admin = await prisma.user.upsert({
    where: { email: adminEmail },
    update: { role: "ADMIN", isActive: true },
    create: {
      email: adminEmail,
      name: "Laboratory Administrator",
      role: "ADMIN",
      passwordHash: await bcrypt.hash(adminPassword, 12),
    },
  });
  console.log(`  ✓ Administrator  ${admin.email}`);

  // ── Client with a portal account ──
  const customerEmail = (
    process.env.SEED_CUSTOMER_EMAIL ?? "research@nordpeak.example"
  ).toLowerCase();
  const customerPassword =
    process.env.SEED_CUSTOMER_PASSWORD ?? "ChangeMe!2026";

  const clientUser = await prisma.user.upsert({
    where: { email: customerEmail },
    update: { isActive: true },
    create: {
      email: customerEmail,
      name: "Dr. Elena Marchetti",
      role: "CUSTOMER",
      passwordHash: await bcrypt.hash(customerPassword, 12),
    },
  });

  const nordpeak = await prisma.customer.upsert({
    where: { userId: clientUser.id },
    update: {},
    create: {
      userId: clientUser.id,
      companyName: "Nordpeak Research Chemicals",
      contactPerson: "Dr. Elena Marchetti",
      email: customerEmail,
      phone: "+44 20 7946 0812",
      vatNumber: "GB402117285",
      marketingOptIn: true,
      shippingLine1: "Unit 12, Kelvin Science Park",
      shippingLine2: "Maryhill Road",
      shippingCity: "Glasgow",
      shippingState: "Scotland",
      shippingPostalCode: "G20 9BT",
      shippingCountry: "United Kingdom",
      billingLine1: "Unit 12, Kelvin Science Park",
      billingCity: "Glasgow",
      billingPostalCode: "G20 9BT",
      billingCountry: "United Kingdom",
      internalNotes:
        "Long-standing account. Consolidated monthly invoicing agreed from March 2026.",
    },
  });
  console.log(`  ✓ Client         ${nordpeak.companyName}`);

  // ── Client without a portal account (anonymous submission) ──
  const helix = await prisma.customer.create({
    data: {
      companyName: "Helix Supply Group",
      contactPerson: "James Okonkwo",
      email: "ops@helixsupply.example",
      phone: "+1 (312) 555-0184",
      shippingLine1: "4400 W Belmont Ave",
      shippingCity: "Chicago",
      shippingState: "IL",
      shippingPostalCode: "60641",
      shippingCountry: "United States",
      billingLine1: "4400 W Belmont Ave",
      billingCity: "Chicago",
      billingPostalCode: "60641",
      billingCountry: "United States",
    },
  });
  console.log(`  ✓ Client         ${helix.companyName}`);

  // ── Orders ──
  const year = new Date().getUTCFullYear();
  const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000);

  const order1 = await prisma.order.create({
    data: {
      orderNumber: `LAVA-ORD-${year}-000101`,
      customerId: nordpeak.id,
      status: "COMPLETED",
      subtotalCents: 97_500,
      discountCents: 0,
      totalCents: 97_500,
      paymentMethod: "INVOICE",
      paymentStatus: "PAID",
      submittedAt: daysAgo(28),
      acceptedAt: daysAgo(27),
      receivedAt: daysAgo(24),
      testingAt: daysAgo(23),
      completedAt: daysAgo(18),
      specialInstructions:
        "Please retain material for a possible follow-up residual solvents panel.",
      samples: {
        create: [
          {
            sampleCode: `LAVA-S-${year}-001001`,
            productName: "BPC-157",
            batchNumber: "NP-240612-A",
            strength: "10 mg",
            quantity: 2,
            expectedPeptide: "BPC-157 (GEPPPGKPADDAGLV)",
            testPurity: true,
            testIdentity: true,
            testContent: true,
            testPhoto: true,
            lineTotalCents: 47_500,
          },
          {
            sampleCode: `LAVA-S-${year}-001002`,
            productName: "Semax",
            batchNumber: "NP-240612-B",
            strength: "10 mg",
            quantity: 1,
            expectedPeptide: "Semax (MEHFPGP)",
            testPurity: true,
            testIdentity: true,
            testContent: true,
            testHeavyMetals: true,
            testPhoto: true,
            lineTotalCents: 57_500,
          },
        ],
      },
      events: {
        create: [
          {
            status: "PENDING",
            note: "Submission received via the online form.",
            createdAt: daysAgo(28),
            emailSent: true,
          },
          {
            status: "ACCEPTED",
            note: "Accepted. Scope confirmed against the requested panel.",
            createdAt: daysAgo(27),
            emailSent: true,
            createdBy: adminEmail,
          },
          {
            status: "SAMPLE_RECEIVED",
            note: "Three vials received. Seals intact, cake appearance normal.",
            createdAt: daysAgo(24),
            emailSent: true,
            createdBy: adminEmail,
          },
          {
            status: "TESTING",
            note: "On instrument — RP-HPLC and LC-MS.",
            createdAt: daysAgo(23),
            emailSent: true,
            createdBy: adminEmail,
          },
          {
            status: "AWAITING_RESULTS",
            note: "Data with the reviewing analyst.",
            createdAt: daysAgo(20),
            emailSent: true,
            createdBy: adminEmail,
          },
          {
            status: "COMPLETED",
            note: "Certificates issued.",
            createdAt: daysAgo(18),
            createdBy: adminEmail,
          },
        ],
      },
    },
    include: { samples: true },
  });

  const order2 = await prisma.order.create({
    data: {
      orderNumber: `LAVA-ORD-${year}-000118`,
      customerId: helix.id,
      status: "TESTING",
      subtotalCents: 70_000,
      discountCents: 0,
      expediteCents: 14_000,
      totalCents: 84_000,
      isExpedited: true,
      paymentMethod: "CARD",
      submittedAt: daysAgo(6),
      acceptedAt: daysAgo(6),
      receivedAt: daysAgo(3),
      testingAt: daysAgo(2),
      samples: {
        create: [
          {
            sampleCode: `LAVA-S-${year}-001044`,
            productName: "Retatrutide",
            batchNumber: "HX-2604-11",
            strength: "10 mg",
            quantity: 1,
            expectedPeptide: "Retatrutide (LY3437943)",
            testPurity: true,
            testIdentity: true,
            testContent: true,
            testEndotoxin: true,
            testPhoto: true,
            lineTotalCents: 70_000,
          },
        ],
      },
      events: {
        create: [
          {
            status: "PENDING",
            note: "Submission received via the online form.",
            createdAt: daysAgo(6),
            emailSent: true,
          },
          {
            status: "ACCEPTED",
            note: "Accepted and flagged for expedited processing.",
            createdAt: daysAgo(6),
            emailSent: true,
            createdBy: adminEmail,
          },
          {
            status: "SAMPLE_RECEIVED",
            note: "Two vials received, including the dedicated endotoxin vial.",
            createdAt: daysAgo(3),
            emailSent: true,
            createdBy: adminEmail,
          },
          {
            status: "TESTING",
            note: "On instrument.",
            createdAt: daysAgo(2),
            emailSent: true,
            createdBy: adminEmail,
          },
        ],
      },
    },
    include: { samples: true },
  });

  const order3 = await prisma.order.create({
    data: {
      orderNumber: `LAVA-ORD-${year}-000124`,
      customerId: nordpeak.id,
      status: "PENDING",
      subtotalCents: 35_000,
      totalCents: 35_000,
      paymentMethod: "INVOICE",
      submittedAt: daysAgo(1),
      samples: {
        create: [
          {
            sampleCode: `LAVA-S-${year}-001051`,
            productName: "MOTS-c",
            batchNumber: "NP-240701-A",
            strength: "10 mg",
            quantity: 1,
            testPurity: true,
            testIdentity: true,
            testPhoto: true,
            lineTotalCents: 35_000,
          },
        ],
      },
      events: {
        create: [
          {
            status: "PENDING",
            note: "Submission received via the online form.",
            createdAt: daysAgo(1),
            emailSent: true,
          },
        ],
      },
    },
  });

  console.log(`  ✓ Orders         3 created`);

  // ── Certificates ──
  type SeedCertificate = {
    number: string;
    customerId: string;
    customerName: string;
    orderId: string | null;
    sampleId: string | null;
    product: string;
    batch: string;
    result: CertificateResult;
    purity: string | null;
    content: string | null;
    status: "VERIFIED" | "PRIVATE" | "REVOKED";
    issuedDaysAgo: number;
    summary: string;
    testedFor: string[];
    revocationReason?: string;
  };

  const specs: SeedCertificate[] = [
    {
      number: `LAVA-${year}-000184`,
      customerId: nordpeak.id,
      customerName: nordpeak.companyName,
      orderId: order1.id,
      sampleId: order1.samples[0].id,
      product: "BPC-157",
      batch: "NP-240612-A",
      result: "PASS",
      purity: "99.12",
      content: "9.84",
      status: "VERIFIED",
      issuedDaysAgo: 18,
      summary:
        "Main-peak purity 99.12% by RP-HPLC at 214 nm. Observed monoisotopic mass consistent with the theoretical sequence mass within 2.1 ppm. Net peptide content 9.84 mg per vial against a 10 mg label claim.",
      testedFor: [
        "Purity",
        "Identity Confirmation",
        "Net Peptide Content",
        "Documented Vial Photography",
      ],
    },
    {
      number: `LAVA-${year}-000185`,
      customerId: nordpeak.id,
      customerName: nordpeak.companyName,
      orderId: order1.id,
      sampleId: order1.samples[1].id,
      product: "Semax",
      batch: "NP-240612-B",
      result: "PASS",
      purity: "98.47",
      content: "9.62",
      status: "VERIFIED",
      issuedDaysAgo: 18,
      summary:
        "Main-peak purity 98.47% by RP-HPLC. Identity confirmed within 3.4 ppm. All Class 1 and Class 2A elemental impurities below the limits of quantitation.",
      testedFor: [
        "Purity",
        "Identity Confirmation",
        "Net Peptide Content",
        "Elemental Impurities",
        "Documented Vial Photography",
      ],
    },
    {
      number: `LAVA-${year}-000191`,
      customerId: helix.id,
      customerName: helix.companyName,
      orderId: null,
      sampleId: null,
      product: "Tirzepatide",
      batch: "HX-2603-07",
      result: "FAIL",
      purity: "91.38",
      content: "7.21",
      status: "VERIFIED",
      issuedDaysAgo: 34,
      summary:
        "Main-peak purity 91.38%, below the client specification of 98%. A significant related substance was resolved at RRT 0.94, accounting for 5.8% of total peak area. Net peptide content 7.21 mg against a 10 mg label claim.",
      testedFor: ["Purity", "Identity Confirmation", "Net Peptide Content"],
    },
    {
      number: `LAVA-${year}-000203`,
      customerId: helix.id,
      customerName: helix.companyName,
      orderId: order2.id,
      sampleId: order2.samples[0].id,
      product: "Retatrutide",
      batch: "HX-2604-11",
      result: "PASS",
      purity: "99.41",
      content: "9.91",
      status: "PRIVATE",
      issuedDaysAgo: 0,
      summary:
        "Awaiting second-analyst review. Not yet released — verification reports this certificate as not found.",
      testedFor: [
        "Purity",
        "Identity Confirmation",
        "Net Peptide Content",
        "Bacterial Endotoxins",
      ],
    },
    {
      number: `LAVA-${year}-000167`,
      customerId: nordpeak.id,
      customerName: nordpeak.companyName,
      orderId: null,
      sampleId: null,
      product: "Selank",
      batch: "NP-240501-C",
      result: "PASS",
      purity: "97.80",
      content: null,
      status: "REVOKED",
      issuedDaysAgo: 52,
      summary:
        "Superseded. See the revocation reason below and the reissued certificate.",
      testedFor: ["Purity", "Identity Confirmation"],
      revocationReason:
        "Transcription error in the reported batch number. Superseded by a corrected certificate issued to the same client on the following business day.",
    },
  ];

  for (const spec of specs) {
    const verificationToken = token();
    const issuedDate = daysAgo(spec.issuedDaysAgo);

    const pdf = placeholderPdf(
      `Certificate of Analysis — ${spec.number}`,
      `${spec.product} · Batch ${spec.batch} · ${spec.customerName}`,
    );

    const hash = certificateHash({
      certificateNumber: spec.number,
      customerName: spec.customerName,
      product: spec.product,
      batchNumber: spec.batch,
      issuedDate,
      pdfSha256: sha256Hex(pdf),
    });

    const certificate = await prisma.certificate.create({
      data: {
        certificateNumber: spec.number,
        verificationToken,
        customerId: spec.customerId,
        orderId: spec.orderId,
        sampleId: spec.sampleId,
        customerName: spec.customerName,
        product: spec.product,
        batchNumber: spec.batch,
        testedFor: spec.testedFor,
        result: spec.result,
        purityResult: spec.purity,
        contentResult: spec.content,
        summary: spec.summary,
        signedBy: "Dr. Marcus Feld",
        signedTitle: "Reviewing Analyst",
        issuedDate,
        hash,
        // Set immediately after creation, once the id is known.
        pdfPath: "",
        pdfSizeBytes: pdf.byteLength,
        status: spec.status,
        releasedAt: spec.status === "VERIFIED" ? issuedDate : null,
        revokedAt: spec.status === "REVOKED" ? daysAgo(40) : null,
        revocationReason: spec.revocationReason ?? null,
        viewCount: spec.status === "VERIFIED" ? 3 + (spec.issuedDaysAgo % 17) : 0,
        createdBy: adminEmail,
      },
    });

    const pdfPath = `certificates/${certificate.id}/r1/coa.pdf`;
    await writeLocalObject(pdfPath, pdf);
    await prisma.certificate.update({
      where: { id: certificate.id },
      data: { pdfPath },
    });

    if (spec.status === "VERIFIED") {
      console.log(
        `  ✓ Certificate    ${spec.number}  →  /verify/${verificationToken}`,
      );
    } else {
      console.log(`  ✓ Certificate    ${spec.number}  (${spec.status})`);
    }
  }

  // ── Invoice ──
  await prisma.invoice.create({
    data: {
      invoiceNumber: `LAVA-INV-${year}-000044`,
      orderId: order1.id,
      customerId: nordpeak.id,
      status: "PAID",
      subtotalCents: 97_500,
      totalCents: 97_500,
      issuedDate: daysAgo(18),
      dueDate: daysAgo(4),
      paidAt: daysAgo(9),
      lineItems: [
        { description: "BPC-157 (NP-240612-A) — Purity", amountCents: 20_000 },
        {
          description: "BPC-157 (NP-240612-A) — Identity Confirmation",
          amountCents: 15_000,
        },
        {
          description: "BPC-157 (NP-240612-A) — Net Peptide Content",
          amountCents: 12_500,
        },
        { description: "Semax (NP-240612-B) — Purity", amountCents: 20_000 },
        {
          description: "Semax (NP-240612-B) — Identity Confirmation",
          amountCents: 15_000,
        },
        {
          description: "Semax (NP-240612-B) — Net Peptide Content",
          amountCents: 12_500,
        },
        {
          description: "Semax (NP-240612-B) — Elemental Impurities",
          amountCents: 10_000,
        },
      ],
    },
  });

  await prisma.invoice.create({
    data: {
      invoiceNumber: `LAVA-INV-${year}-000051`,
      orderId: order2.id,
      customerId: helix.id,
      status: "SENT",
      subtotalCents: 70_000,
      totalCents: 84_000,
      issuedDate: daysAgo(2),
      dueDate: new Date(Date.now() + 12 * 86_400_000),
      lineItems: [
        {
          description: "Retatrutide (HX-2604-11) — Purity",
          amountCents: 20_000,
        },
        {
          description: "Retatrutide (HX-2604-11) — Identity Confirmation",
          amountCents: 15_000,
        },
        {
          description: "Retatrutide (HX-2604-11) — Net Peptide Content",
          amountCents: 12_500,
        },
        {
          description: "Retatrutide (HX-2604-11) — Bacterial Endotoxins",
          amountCents: 17_500,
        },
        {
          description: "Expedited processing surcharge",
          amountCents: 14_000,
        },
      ],
    },
  });
  console.log("  ✓ Invoices       2 created");

  // ── Notifications & messages ──
  await prisma.notification.createMany({
    data: [
      {
        customerId: nordpeak.id,
        title: `Certificate LAVA-${year}-000184 released`,
        body: "Your Certificate of Analysis for BPC-157 (batch NP-240612-A) is ready to view.",
        href: "/dashboard/certificates",
        icon: "certificate",
        createdAt: daysAgo(18),
      },
      {
        customerId: nordpeak.id,
        title: `Order ${order3.orderNumber} received`,
        body: "We have logged your submission. Ship your samples quoting this order number.",
        href: "/dashboard/orders",
        icon: "package",
        createdAt: daysAgo(1),
      },
    ],
  });

  await prisma.message.create({
    data: {
      name: "Sarah Lindqvist",
      email: "sarah@meridianpeptide.example",
      company: "Meridian Peptide Labs",
      phone: "+46 8 123 456",
      subject: "Method suitability for a cyclic peptide",
      body:
        "We have a head-to-tail cyclised 11-mer that has given us inconsistent purity results at two other laboratories. " +
        "Before we submit, could you confirm whether your standard RP-HPLC gradient resolves cyclic from linear forms, " +
        "or whether we should request a modified method? Happy to send the sequence under NDA.",
      status: "UNREAD",
      createdAt: daysAgo(2),
    },
  });
  console.log("  ✓ Notifications  2 created");
  console.log("  ✓ Messages       1 created");

  // ── Audit trail ──
  await prisma.activityLog.createMany({
    data: [
      {
        userId: admin.id,
        actorEmail: adminEmail,
        action: "certificate.released",
        entity: "Certificate",
        metadata: { certificateNumber: `LAVA-${year}-000184`, emailSent: true },
        createdAt: daysAgo(18),
      },
      {
        userId: admin.id,
        actorEmail: adminEmail,
        action: "certificate.revoked",
        entity: "Certificate",
        metadata: {
          certificateNumber: `LAVA-${year}-000167`,
          reason: "Transcription error in the reported batch number.",
        },
        createdAt: daysAgo(40),
      },
      {
        userId: admin.id,
        actorEmail: adminEmail,
        action: "order.status_changed",
        entity: "Order",
        entityId: order2.id,
        metadata: { from: "SAMPLE_RECEIVED", to: "TESTING" },
        createdAt: daysAgo(2),
      },
    ],
  });
  console.log("  ✓ Audit entries  3 created");

  const released = await prisma.certificate.findMany({
    where: { status: "VERIFIED" },
    select: { certificateNumber: true, verificationToken: true },
  });

  console.log("\n  ── Sign in ──────────────────────────────────────────");
  console.log(`  Admin     ${adminEmail} / ${adminPassword}`);
  console.log(`  Client    ${customerEmail} / ${customerPassword}`);
  console.log("\n  ── Try verification ─────────────────────────────────");
  for (const certificate of released) {
    console.log(`  ${certificate.certificateNumber}`);
  }
  console.log(
    `\n  Or scan-equivalent: /verify/${released[0]?.verificationToken}\n`,
  );
}

main()
  .catch((error) => {
    console.error("\n✗ Seed failed:\n", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
